### ISSUE TITLE
eo-math: wrappers for int and float

### ISSUE THREAD

**Issue by yegor256** [objectionary/home#10]
Would be great to have decorators for numbers, with additional math features, for example:

```
+import org.eolang.math.cos

3.1415926 > pi
cos pi > x
```

Here, `x` would be _cosinus_ of `pi`. You can get some inspiration here: https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html

**Comment by maxonfjvipon** [comment]
Hey, @yegor256 
I'm trying to create some decorators for numbers and I have a questions: 
1. What's the right way to create a constant numbers like PI or E(Euler's number)? 
1. How many digits after dot is enough? 
1. What are good tests for these constant numbers?
```
+package org.eolang.math
+rt jvm org.eolang:eo-runtime:0.21.9

3.141592653589793 > pi /float

# or

[] > pi /float
  3.141592653589793 > @

# Tests
+package org.eolang.math
+alias org.eolang.math.pi
+junit

[] > pi-value-is-correct
  pi.eq 3.141592653589793 > @

```

**Comment by yegor256** [comment]
@maxonfjvipon can you please post a URL of your `eo-math` GitHub repository here?

**Comment by maxonfjvipon** [comment]
> @maxonfjvipon can you please post a URL of your `eo-math` GitHub repository here?

@yegor256 I haven't created it yet. Should I?

**Comment by yegor256** [comment]
@maxonfjvipon yes, please. This definitely should be a separate module, in a separate repo. Once you create it, we move it to @objectionary organization and will maintain together with others. If you don't mind.

**Comment by maxonfjvipon** [comment]
> @maxonfjvipon yes, please. This definitely should be a separate module, in a separate repo. Once you create it, we move it to @objectionary organization and will maintain together with others. If you don't mind.

@yegor256 Sure. I'll do it. Could you please send an example of the repo so I do it right?

**Comment by yegor256** [comment]
@maxonfjvipon this one is a good example: https://github.com/Graur/eo-hamcrest/ (it's still in development)

**Comment by maxonfjvipon** [comment]
@yegor256 here: https://github.com/maxonfjvipon/eo-math
