### ISSUE TITLE
eo-threads: concurrency

### ISSUE THREAD

**Issue by yegor256** [objectionary/home#14]
Would be great to let EO programs run in many threads.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#24](https://github.com/objectionary/home/issues/24) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#24](https://github.com/objectionary/home/issues/24) is solved here.

**Comment by yegor256** [comment]
here: https://github.com/objectionary/eo-threads
