### ISSUE TITLE
eo-collections: sets, lists, maps, queues, etc.

### ISSUE THREAD

**Issue by yegor256** [objectionary/home#15]
Would be great to have objects for sets, lists, maps, queues, and so on.

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#23](https://github.com/objectionary/home/issues/23) is still not solved.

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#23](https://github.com/objectionary/home/issues/23) is solved here.
