### ISSUE TITLE
eo-strings: rich string manipulations

### ISSUE THREAD

**Issue by yegor256** [objectionary/home#21]
Let's create a new library of EO objects for string manipulations. Should work like this:

```
+alias org.eolang.strings.rs

"Hello, world!  " > s1
rs s > s2
s2.trim > s3
```

Let's implement most of what these libraries provide:

 * https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html
 * https://guava.dev/releases/19.0/api/docs/com/google/common/base/Strings.html
 * https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/StringUtils.html
 * https://ruby-doc.org/core-3.1.2/String.html

**Comment by yegor256** [comment]
@fizruk it's yours

**Comment by yegor256** [comment]
@EugeneDar it's yours now

**Comment by EugeneDar** [comment]
@yegor256 sure, will do it.
