### ISSUE TITLE
to add information about `pull.sh` script in README.md

### ISSUE THREAD

**Issue by Graur** [objectionary/home#38]
@Graur by hand :D I did not noticed `pull.sh`... Will try it next time, thanks!) 

UPD: mb you should add something about `pull.sh` to readme? I believe i'm not the last who make changes in that way)

_Originally posted by @maxonfjvipon in https://github.com/objectionary/home/issues/37#issuecomment-1179546650_

**Comment by yegor256** [comment]
@Graur I added some explanation in f611f77 If still not enough, let me know. Otherwise, please close.

**Comment by Graur** [comment]
@yegor256 Great! Thank you!
