### ISSUE TITLE
updating `tags.txt`

### ISSUE THREAD

**Issue by IngeniariusSoftware** [objectionary/home#53]
@yegor256, is it ok that the new version 0.27.2 is still not in the list or has something changed?

https://home.objectionary.com/tags.txt

```
ff5b0add102f446161b125d72002939ee7e369f8	gh-pages
00b60c7b2112cbad4e37ba96b162469a0e75f6df	master
5fe5ad8d21dbe418038fa4c86e096fb037f290a9	0.23.15
15c85d7f8cffe15b0deba96e90bdac98a76293bb	0.23.17
4b19944d86058e3c81e558340a3a13bc335a2b48	0.23.19
0aa6875c40d099c3f670e93d4134b629566c5643	0.25.0
ff32e9ff70c2b3be75982757f4b0607dc37b258a	0.25.5
e0b783692ef749bb184244acb2401f551388a328	0.26.0
cc554ab82909eebbfdacd8a840f9cf42a99b64cf	0.27.0
```

**Comment by yegor256** [comment]
@IngeniariusSoftware this is a bug. our workflow doesn't get triggered on `git push` with a tag: https://github.com/objectionary/home/blob/master/.github/workflows/pages.yml#L2-L8

**Comment by yegor256** [comment]
@mximp please, help here

**Comment by mximp** [comment]
@IngeniariusSoftware Fixed now. The file should be refreshed after next release.
@yegor256 BTW when is it expected?

**Comment by yegor256** [comment]
@mximp did just now, pushed tag 0.28.0
