### ISSUE TITLE
eo-hamcrest: unit tests assertions

### ISSUE THREAD

**Issue by yegor256** [objectionary/home#6]
Would be great to create a EO version of http://hamcrest.org/ with assertions for unit tests. Something like this:

```
+junit
+import org.hamcrest.assert-that
+import org.hamcrest.equal-to

[] > arithmetic-add-works
  assert-that > @
    equal-to
      "sum of two numbers"
      5.add 1
      6
```

If the test fails, the log output must contain nice message, just like it works with other Hamcrest libraries.

**Comment by Graur** [comment]
Hi, @yegor256
I want to create EO version of hamcrest and I have two questions:

1) Do we need to implement our own matchers in `.eo` files in this project, or somehow use the original hamcrest jar?
2) What kind of matches we need to implement first? I suggest:
- `equalTo `
- `not`
- numbers: `greaterThan, lessThan`
- strings: `equalToIgnoringCase,  containsString, endsWith, startsWith`

Could you, please, provide me some help with these questions?

**Comment by yegor256** [comment]
@Graur yes, I would start with `equal-to`, `greater-than`, etc. I'm not sure about hamcrest usage, though. I would first try to implement it without Hamcrest and see how hard it would be.

**Comment by Graur** [comment]
Thanks. I start a new repository for this purposes: [eo-tests](https://github.com/Graur/eo-tests/)

**Comment by Graur** [comment]
@yegor256  What do you think about this two examples?
```
+package org.eolang
+alias org.eolang.test.assert-equals

[] > a
  assert-equals > @
    "two numbers"
    5.add 1
    6
```

```
+package org.eolang
+alias org.eolang.test.assert-gt

[] > b
  assert-gt > @
    "one number greater than another one"
    5.add 6
    8
```

The main idea is to exclude unnecessary object ```assert-that``` from the issue example.

**Comment by Graur** [comment]
I also create an alternative repository with hamcrest library for EOLANG: https://github.com/Graur/eo-hamcrest-2.
I think it's closely to canonical hamcrest library with number of matchers as different objects.

**Comment by Graur** [comment]
I have one more idea about eo-hamcrest:
```
[] > two-num
  assert-that > @
  .reason "is two numbers is equal?"
  .actual 4
  .equal-to 3.add 1
  .or
  .less-than 100.div 10

```
WDYT ?

**Comment by yegor256** [comment]
it's here https://github.com/Graur/eo-hamcrest/

**Comment by yegor256** [comment]
@Graur I believe it's done, closing
