### ISSUE TITLE
let's enable .rultor.yml in this repository

### ISSUE THREAD

**Issue by yegor256** [objectionary/home#84]
We don't have `.rultor.yml` here, that's why can't `merge`. Let's add this config file with only `merge` section.

**Comment by yegor256** [comment]
@mximp please, help

**Comment by mximp** [comment]
@c71n93 please assist

**Comment by c71n93** [comment]
> @c71n93 please assist

Ok

**Comment by mximp** [comment]
@yegor256 Please check and close

**Comment by yegor256** [comment]
@mximp thanks!
