### ISSUE TITLE
Create an index with all object names within Objectionary

### ISSUE THREAD

**Issue by mximp** [objectionary/home#96]
Follow up on https://github.com/objectionary/eo/issues/1705.

Let's have a file available `objectionary-index.txt` containing all fully-qualified object names:
```
org.eolang.int
org.eolang.bool
org.eolang.hamcrest.assert-that
....
```

It will be used by users to quickly identify if an object is within Objectionary.

**Comment by mximp** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@mximp good idea. All we need to do is to make a simple script (using `xmllint`) that would go through all `.xmir` files and extract `@loc` attributes from all `<o/>` objects

**Comment by volodya-lombrozo** [comment]
Would it be better to use tree-like structure and common-used format for parsing (json, yaml, xml)?

**Comment by mximp** [comment]
> Would it be better to use tree-like structure and common-used format for parsing (json, yaml, xml)?

@volodya-lombrozo I believe plain list is easier to collect. And in this case we don't need a hierarchy.

**Comment by volodya-lombrozo** [comment]
@mximp The next command:
```
xmllint --xpath '//o/@loc' array.xmir | sed -n 's/[^\"]*\"\([^\"]*\)\"[^\"]*/\1\n/gp'
```
Gives me the next output:
```
Φ.org.eolang.array
Φ.org.eolang.array.empty
Φ.org.eolang.array.empty.α0
Φ.org.eolang.array.empty.α1
Φ.org.eolang.array.empty.α2
Φ.org.eolang.array.length
Φ.org.eolang.array.length.α0
Φ.org.eolang.array.length.α1
Φ.org.eolang.array.length.α2
Φ.org.eolang.array.at
Φ.org.eolang.array.at.α0
Φ.org.eolang.array.at.α1
Φ.org.eolang.array.at.α2
Φ.org.eolang.array.with
Φ.org.eolang.array.with.α0
Φ.org.eolang.array.with.α1
Φ.org.eolang.array.with.α2
Φ.org.eolang.array$empty
Φ.org.eolang.array$empty.φ
Φ.org.eolang.array$empty.length
Φ.org.eolang.array$empty.at
Φ.org.eolang.array$empty.with
Φ.org.eolang.array$length
Φ.org.eolang.array$length.empty
Φ.org.eolang.array$length.at
Φ.org.eolang.array$length.with
Φ.org.eolang.array$at
Φ.org.eolang.array$at.i
Φ.org.eolang.array$at.empty
Φ.org.eolang.array$at.length
Φ.org.eolang.array$at.with
Φ.org.eolang.array$with
Φ.org.eolang.array$with.x
Φ.org.eolang.array$with.empty
Φ.org.eolang.array$with.length
Φ.org.eolang.array$with.at
```
Hope it will help
